-- MySQL Script generated by MySQL Workbench
-- Sat Jul 27 20:20:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema springpractice
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema springpractice
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `springpractice` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`BOARD_CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BOARD_CATEGORY` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;

USE `springpractice` ;

-- -----------------------------------------------------
-- Table `springpractice`.`user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springpractice`.`user_info` (
  `id` VARCHAR(30) NOT NULL,
  `pwd` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(30) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `type` VARCHAR(1) NOT NULL DEFAULT 'M',
  `status` VARCHAR(1) NOT NULL DEFAULT '1',
  `profile` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = '전체유저공통 테이블';


-- -----------------------------------------------------
-- Table `springpractice`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springpractice`.`admin` (
  `admin_id` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`admin_id`),
  INDEX `fk_admin_idx` (`admin_id` ASC) VISIBLE,
  CONSTRAINT `fk_admin`
    FOREIGN KEY (`admin_id`)
    REFERENCES `springpractice`.`user_info` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `springpractice`.`board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springpractice`.`board` (
  `bno` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `content` TEXT NOT NULL,
  `writer` VARCHAR(30) NOT NULL,
  `view_cnt` INT NULL DEFAULT '0',
  `comment_cnt` INT NULL DEFAULT '0',
  `reg_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `up_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `files_no` BIGINT NULL DEFAULT NULL,
  `BOARD_CATEGORY_category_id` INT NOT NULL,
  PRIMARY KEY (`bno`, `BOARD_CATEGORY_category_id`),
  INDEX `fk_board_BOARD_CATEGORY1_idx` (`BOARD_CATEGORY_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_board_BOARD_CATEGORY1`
    FOREIGN KEY (`BOARD_CATEGORY_category_id`)
    REFERENCES `mydb`.`BOARD_CATEGORY` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 228
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `springpractice`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springpractice`.`comment` (
  `cno` INT NOT NULL AUTO_INCREMENT,
  `bno` INT NOT NULL,
  `pcno` INT NULL DEFAULT NULL,
  `comment` VARCHAR(3000) NULL DEFAULT NULL,
  `commenter` VARCHAR(30) NULL DEFAULT NULL,
  `reg_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `up_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cno`))
ENGINE = InnoDB
AUTO_INCREMENT = 112
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `springpractice`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springpractice`.`files` (
  `file_no` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `original_name` VARCHAR(255) NOT NULL,
  `stored_name` VARCHAR(255) NOT NULL,
  `file_type` VARCHAR(50) NOT NULL,
  `file_size` BIGINT NOT NULL,
  `file_path` VARCHAR(255) NOT NULL,
  `uploaded_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` VARCHAR(30) NOT NULL,
  `associated_object_id` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`file_no`),
  UNIQUE INDEX `id` (`file_no` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'xxx';


-- -----------------------------------------------------
-- Table `springpractice`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springpractice`.`member` (
  `mem_id` VARCHAR(30) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(11) NULL DEFAULT NULL,
  `zipcode` INT NULL DEFAULT NULL,
  `add_normal` VARCHAR(100) NULL DEFAULT NULL,
  `add_detail` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`mem_id`),
  INDEX `fk_mem_id_idx` (`mem_id` ASC) VISIBLE,
  CONSTRAINT `fk_mem_id`
    FOREIGN KEY (`mem_id`)
    REFERENCES `springpractice`.`user_info` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = '일반회원테이블';


-- -----------------------------------------------------
-- Table `springpractice`.`board_has_user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springpractice`.`board_has_user_info` (
  `board_bno` INT NOT NULL,
  `user_info_id` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`board_bno`, `user_info_id`),
  INDEX `fk_board_has_user_info_user_info1_idx` (`user_info_id` ASC) VISIBLE,
  INDEX `fk_board_has_user_info_board1_idx` (`board_bno` ASC) VISIBLE,
  CONSTRAINT `fk_board_has_user_info_board1`
    FOREIGN KEY (`board_bno`)
    REFERENCES `springpractice`.`board` (`bno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_board_has_user_info_user_info1`
    FOREIGN KEY (`user_info_id`)
    REFERENCES `springpractice`.`user_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
